parameters:
    debug.debugger_detector.class: Flying\Bundle\DebugBundle\DebuggerDetector\EventListener\DebuggerDetectorListener

    debug.csrf.csrf_provider.class: Flying\Bundle\DebugBundle\Csrf\DebugCsrfProvider
    debug.csrf.token_manager.class: Flying\Bundle\DebugBundle\Csrf\DebugCsrfTokenManager

    debug.security.auth_provider.class: Flying\Bundle\DebugBundle\Security\Authentication\DebugAuthenticationProvider
    debug.security.auth_listener.class: Flying\Bundle\DebugBundle\Security\Firewall\DebugAuthenticationListener

services:
    debug.debugger_detector:
        class: %debug.debugger_detector.class%
        tags:
            - { name: kernel.event_subscriber }

    debug.csrf.csrf_provider:
        class: %debug.csrf.csrf_provider.class%
        arguments: [@form.csrf_provider]
        tags:
            - { name: debug.debugger_status.subscriber }

    debug.csrf.token_manager:
        class: %debug.csrf.token_manager.class%
        arguments: [@security.csrf.token_manager]
        tags:
            - { name: debug.debugger_status.subscriber }

    debug.security.auth_provider:
        class: %debug.security.auth_provider.class%

    debug.security.auth_listener:
        class: %debug.security.auth_listener.class%
        arguments: [@security.context, @debug.security.auth_provider]
        tags:
            - { name: debug.debugger_status.subscriber }
