parameters:
    debug_csrf.debug_token_manager.class: Flying\Bundle\DebugCsrfBundle\Csrf\DebugCsrfTokenManager
    debug_csrf.debugger_detector.class: Flying\Bundle\DebugCsrfBundle\EventListener\DebuggerDetectorListener

services:
    debug_csrf.debug_token_manager:
        class: %debug_csrf.debug_token_manager.class%
        arguments: [@security.csrf.token_manager]
    debug_csrf.debugger_detector:
        class: %debug_csrf.debugger_detector.class%
        arguments: [%kernel.debug%, @debug_csrf.debug_token_manager]
        tags:
            - { name: kernel.event_subscriber }
