parameters:
    debug.debugger_detector.class: Flying\Bundle\DebugBundle\DebuggerDetector\EventListener\DebuggerDetectorListener

    debug.csrf.debug_token_manager.class: Flying\Bundle\DebugBundle\Csrf\DebugCsrfTokenManager

services:
    debug.debugger_detector:
        class: %debug.debugger_detector.class%
        tags:
            - { name: kernel.event_subscriber }

    debug.csrf.debug_token_manager:
        class: %debug.csrf.debug_token_manager.class%
        arguments: [@security.csrf.token_manager]
        tags:
            - { name: debug.debugger_status.subscriber }


